spring.application.name=CliqueDCTCWeb3
spring.datasource.url=jdbc:mysql://clique-db.c384gi8gy3q4.us-east-2.rds.amazonaws.com:3306/cliqueWebIII?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=oftheopera
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
